version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "saved-counter-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ix19f20058ao"
s3_prefix = "saved-counter-stack"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

